package presentacion;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class FrmPrincipal extends javax.swing.JFrame {
     /*Propiedad publica y estatica varacceso*/
    public static String varacceso="";

    /**
     * Creates new form VentanaPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(FrmPrincipal.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        mnuBar = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        mnuRegistro = new javax.swing.JMenu();
        mnuiClientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuiUsuarios = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuiServicios = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuiAcerca = new javax.swing.JMenuItem();
        mnuOpciones = new javax.swing.JMenu();
        mnuiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:. Sistema para el control de Ordenes de Servicio");
        setBackground(new java.awt.Color(0, 51, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        escritorio.setBackground(new java.awt.Color(153, 153, 153));
        escritorio.setPreferredSize(new java.awt.Dimension(780, 625));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        lblUsuario.setText("Usuario");

        lblPerfil.setText("Perfil");

        mnuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/house.png"))); // NOI18N
        mnuInicio.setText("Inicio");
        mnuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuInicioMouseClicked(evt);
            }
        });
        mnuBar.add(mnuInicio);

        mnuRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/Reservas.png"))); // NOI18N
        mnuRegistro.setText("Registro");

        mnuiClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/clientes.png"))); // NOI18N
        mnuiClientes.setText("Clientes");
        mnuiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiClientesActionPerformed(evt);
            }
        });
        mnuRegistro.add(mnuiClientes);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/computer32.png"))); // NOI18N
        jMenuItem1.setText("Orden Servicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuRegistro.add(jMenuItem1);

        mnuiUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/user32.png"))); // NOI18N
        mnuiUsuarios.setText("Usuarios");
        mnuiUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiUsuariosActionPerformed(evt);
            }
        });
        mnuRegistro.add(mnuiUsuarios);

        mnuBar.add(mnuRegistro);

        mnuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/stats32.png"))); // NOI18N
        mnuReportes.setText("Reportes");

        mnuiServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/report.png"))); // NOI18N
        mnuiServicios.setText("Servicios");
        mnuReportes.add(mnuiServicios);

        mnuBar.add(mnuReportes);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/Ayuda.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");

        mnuiAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/star32.png"))); // NOI18N
        mnuiAcerca.setText("Acerca de...");
        mnuAyuda.add(mnuiAcerca);

        mnuBar.add(mnuAyuda);

        mnuOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/gear32.png"))); // NOI18N
        mnuOpciones.setText("Opciones");

        mnuiSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivos/house_go.png"))); // NOI18N
        mnuiSalir.setText("Salir");
        mnuiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiSalirActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuiSalir);

        mnuBar.add(mnuOpciones);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(lblPerfil)
                .addContainerGap(513, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblPerfil)))
        );

        setBounds(0, 0, 1024, 739);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date fecha = new Date();
        DateFormat formato = DateFormat.getDateInstance(DateFormat.SHORT);
        //lblFecha.setText("Fecha actual:" + formato.format(fecha));
    }//GEN-LAST:event_formWindowActivated

    private void mnuiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiSalirActionPerformed
        int salir = JOptionPane.showConfirmDialog(null, "Esta seguro que desea salir?", "Atencion", JOptionPane.YES_NO_OPTION);
        if (salir == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuiSalirActionPerformed

    private void mnuiUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiUsuariosActionPerformed
        FrmUsuarios usuarios = new FrmUsuarios();
        usuarios.setVisible(true);
        escritorio.add(usuarios);
    }//GEN-LAST:event_mnuiUsuariosActionPerformed

    private void mnuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuInicioMouseClicked
        this.escritorio.removeAll();
        this.escritorio.repaint();
    }//GEN-LAST:event_mnuInicioMouseClicked

    private void mnuiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiClientesActionPerformed
        FrmClientes usuarios = new FrmClientes();
        usuarios.setVisible(true);
        escritorio.add(usuarios);// TODO add your handling code here:
    }//GEN-LAST:event_mnuiClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmOrdenServicio usuarios = new FrmOrdenServicio();
        usuarios.setVisible(true);
        escritorio.add(usuarios);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JLabel lblPerfil;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuInicio;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenu mnuRegistro;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenuItem mnuiAcerca;
    private javax.swing.JMenuItem mnuiClientes;
    private javax.swing.JMenuItem mnuiSalir;
    public static javax.swing.JMenuItem mnuiServicios;
    public static javax.swing.JMenuItem mnuiUsuarios;
    // End of variables declaration//GEN-END:variables
}
